postgres:
  image: mdillon/postgis:9.5
  ports:
   - "5432:5432"
  environment:
    POSTGRES_DB: osm
    POSTGRES_USER: osm
    POSTGRES_PASSWORD: osm
import-osm:
  build: src/import-osm
  links:
   - postgres:postgres
  volumes:
   - ./data:/data
export-shapefile:
  build: src/export-shapefile
  links:
   - postgres:postgres
  volumes:
   - ./data:/data
calculate-centerlines:
  build: src/calculate-centerlines
  links:
   - postgres:postgres
  volumes:
   - ./data:/data
